name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: coturiv/setup-ionic@v1
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - env: 
        ENVIRONMENT_TEST: ${{ secrets.ENVIRONMENT_TEST }}
        ENVIRONMENT_PROD: ${{ secrets.ENVIRONMENT_PROD }}
    - run: echo "$ENVIRONMENT_TEST" >> src/environments/environment
    - run: echo "$ENVIRONMENT_PROD" >> src/environments/environment.prod
    - run: npm install
    - run: ionic build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
